### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by tomiaijo** [JieHe96/iOS_Tensorflow_ObjectDetection_Example#7]
Hi,

While running the `tensorflow/contrib/makefile/build_all_ios_ssd.sh` script, I encountered the following compilation error:

```
tensorflow/tensorflow/contrib/makefile/gen/protobuf-host/bin/protoc  tensorflow/core/grappler/costs/op_performance_data.proto --cpp_out tensorflow/tensorflow/contrib/makefile/gen/host_obj/
tensorflow/tools/git/gen_git_source.sh tensorflow/core/util/version_info.cc
make: *** No rule to make target `tensorflow/tensorflow/contrib/makefile/gen/obj/ios_ARM64/tensorflow/core/common_runtime/gpu/gpu_tracer.o', needed by `/Users/tomiaijo/tensorflow/tensorflow/contrib/makefile/gen/lib/ios_ARM64/libtensorflow-core-arm64.a'.  Stop.
make: *** Waiting for unfinished jobs....
+ '[' 2 -ne 0 ']'
+ echo 'arm64 compilation failed.'
arm64 compilation failed.
+ exit 1
```

Tensorflow is 1.2 (`e92aed`): 

```
$ cat RELEASE.md | grep "1.2.0"  #make sure the output is "Relase 1.2.0"
# Release 1.2.0
```

Any ideas what might have gone wrong?

**Comment by Christ1992** [comment]
@tomiaijo got the same problem. resolved by using the official tensorflow code though it would be slow.

**Comment by chinaluffy** [comment]
@tomiaijo  got the same problem. resolved by using the official tensorflow code though it would be slow.

![image](https://user-images.githubusercontent.com/31507070/30018665-4fcaee46-9190-11e7-9a59-97b837327ce4.png)

**Comment by JieHe96** [comment]
Just update the example for TensorFlow 1.4.0 @tomiaijo @Christ1992 @chinaluffy
