### ISSUE TITLE
No OpKernel was registered to support Op 'All' with these attrs

### ISSUE THREAD

**Issue by chinaluffy** [JieHe96/iOS_Tensorflow_ObjectDetection_Example#8]
I build the demo ,show this problem . 

Quick Start with tensorflow/contrib/makefile/build_all_ios_ssd.sh . 

Invalid argument: No OpKernel was registered to support Op 'All' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>

	 [[Node: assert_equal/All = All[Tidx=DT_INT32, keep_dims=false](assert_equal/Equal, assert_equal/Const)]]

how to fix this error ?

**Comment by JieHe96** [comment]
I will push the updated version very soon

**Comment by JieHe96** [comment]
Just update the example for TensorFlow 1.4.0 @chinaluffy
