### ISSUE TITLE
nsync directory not generated

### ISSUE THREAD

**Issue by schubertq** [JieHe96/iOS_Tensorflow_ObjectDetection_Example#9]
Hello，Jie，
I met a problem below，even if I use official sh also the same result。
ld: warning: directory not found for option '-L/Users/schubert/Documents/tensorflow-master/tensorflow/contrib/makefile/gen/nsync'
ld: library not found for -lnsync

**Comment by JieHe96** [comment]
Try compiling the nsync lib by:
<img width="1121" alt="screen shot 2017-09-19 at 12 24 30 pm" src="https://user-images.githubusercontent.com/10534493/30611243-b68a61ba-9d35-11e7-817f-576dcd6cab8b.png">

**Comment by schubertq** [comment]
Thank you for your reply, Jie, I solved this problem by typing you mentioned in the tips:
tensorflow/contrib/makefile/build_tflib_ssd.sh
Your solution sh code is contained in the build_all_ios_ssd file, I have run build_all_ios_ssd sh before.
